; Teensy 4.1 Arduino boilerplate (PlatformIO)
; https://docs.platformio.org/page/boards/teensy/teensy41.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

; Serial monitor defaults
monitor_speed = 115200
monitor_filters = send_on_enter
